api:
  rest:
    host: '0.0.0.0'
    port: 3001
    spec: ./openapi.yaml
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Sec-Fetch-Dest
        - Referer
        - Accept
        - User-Agent
        - RA-API-KEY
      allowedMethods:
        - OPTIONS
        - GET
        - POST
log:
  debug: true

datasource:
  type: "postgres"
  host: "postgres"
  port: 5432
  database: "postgres"
  db_username: "postgres"
  db_password: "postgres"
  sslMode: "disable"
  migrations: "db/migrations"
