// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/Test/CovidApp/internal/component"
	"github.com/Test/CovidApp/internal/entrypoint"
	covidapp2 "github.com/Test/CovidApp/internal/entrypoint/controller"
	"github.com/Test/CovidApp/internal/infrastructure/postgres"
	"github.com/Test/CovidApp/internal/infrastructure/postgres/repository"
	"github.com/gorilla/mux"
	"github.com/jinzhu/gorm"
	"github.com/sirupsen/logrus"
	"github.com/spf13/viper"
	"os"
)

// Injectors from wire.go:

func createRestAPI() *rest.API {
	appConfig := ProvideConfig()
	config := ProvideRestAPIConfig(appConfig)
	router := mux.NewRouter()
	datasource := ProvideDatasource(appConfig)
	db := ProvideGormDB(datasource)
	covidappRepository := repository.NewGormRepository(db)
	covidappConfig := ProvideServiceConfig(appConfig)
	service := covidapp.NewCovidApp(covidappRepository, covidappConfig)
	controller := covidapp2.NewController(service)
	api := rest.NewRestAPI(config, router, controller)
	return api
}

func createMigration() *postgres.Migration {
	appConfig := ProvideConfig()
	datasource := ProvideDatasource(appConfig)
	migration := postgres.NewMigration(datasource)
	return migration
}

// wire.go:

func ProvideRestAPIConfig(config AppConfig) *rest.Config {

	var corsConfig rest.CORSConfig
	corsConfig.AllowedOrigins = config.API.REST.CORS.AllowedOrigins
	corsConfig.AllowedHeaders = config.API.REST.CORS.AllowedHeaders
	corsConfig.AllowedMethods = config.API.REST.CORS.AllowedMethods

	restConfig := &rest.Config{
		Host:    config.API.REST.Host,
		Port:    config.API.REST.Port,
		Spec:    config.API.REST.Spec,
		Cors:    corsConfig,
		Version: "local",
	}
	logrus.Info("========================================")
	logrus.Info("API Configuration")
	logrus.Info("========================================")
	logrus.Info("Host:    ", restConfig.Host)
	logrus.Info("Port:    ", restConfig.Port)
	logrus.Info("Spec:    ", restConfig.Spec)
	logrus.Info("Version: ", restConfig.Port)

	return restConfig
}

func ProvideConfig() AppConfig {
	config, err := loadConfig()
	if err != nil {
		logrus.WithError(err).Error("unable to unmarshal configuration")
		os.Exit(1)
	}

	return config
}

func ProvideServiceConfig(config AppConfig) covidapp.Config {
	return covidapp.Config{
		Host: config.API.REST.Host,
		Port: config.API.REST.Port,
		Spec: config.API.REST.Spec,
	}
}

func ProvideDatabaseConfig() *rest.Database {
	var config rest.Database
	err := viper.UnmarshalKey("api.rest", &config)
	if err != nil {
		logrus.WithError(err).Error("unable to read database config")
		os.Exit(1)
	}
	logrus.Info("========================================")
	logrus.Info("API Configuration")
	logrus.Info("========================================")
	logrus.Info("Host:  ", config.DBHost)
	logrus.Info("User:  ", config.DBUser)
	logrus.Info("Conns: ", config.DBConns)

	return &config
}

func ProvideDatasource(config AppConfig) *postgres.Datasource {
	return &postgres.Datasource{
		Type:       config.Datasource.Type,
		Host:       config.Datasource.Host,
		Port:       config.Datasource.Port,
		Database:   config.Datasource.Database,
		Username:   config.Datasource.Username,
		Password:   config.Datasource.Password,
		SSLMode:    config.Datasource.SSLMode,
		Migrations: config.Datasource.Migrations,
	}
}

func ProvideGormDB(datasource *postgres.Datasource) *gorm.DB {
	db, err := gorm.Open("postgres", datasource.AsPQString())
	if err != nil {
		logrus.WithError(err).Error("unable to get gorm db connection")
		os.Exit(1)
	}

	return db
}
